ARG REGION=us-west-2
ARG DOCKERBASE=TBD
ARG ACCOUNT=1
FROM ${ACCOUNT}.dkr.ecr.$REGION.amazonaws.com/${DOCKERBASE}

# COPY all the code into the /opt/ml/code directory,

ADD ./source   /opt/ml/code



#Set PythonPath
ENV PYTHONPATH /opt/ml/code

WORKDIR /opt/ml/code


#Example run
ENTRYPOINT bash
CMD [ "scripts/run_pipeline_download_esindex.sh", "/data" , "human_01*.xml"]
